"""Export a Studio design (A-Box) into the engine's real Cardinal spec bundle,
and validate it by loading it through the engine's own loader + DAG builder.

This is Step 1: the Builder produces a complete, runnable spec a data engineer can
open and `cardinal validate`. It maps the ontology's vocabulary to the engine's
spec language (snake_case grains/mechanisms/dist families). Distribution params and
real billing arithmetic are Tier-1 work (Step 2); entered fields carry the intended
family with `calibration: pending` so it's explicit they still need calibration.
"""
from __future__ import annotations
import io
import shutil
import tempfile
import zipfile
from pathlib import Path

import yaml
from rdflib import RDF, URIRef

try:
    from .ontology_service import included_fields, local, CARD, BILL
except ImportError:
    from ontology_service import included_fields, local, CARD, BILL

DCT_SOURCE = URIRef("http://purl.org/dc/terms/source")

GRAIN = {"AccountCycle": "account_cycle", "Account": "account"}
DTYPE = {"decimal": "float64", "boolean": "int64", "int64": "int64",
         "string": "str", "date": "str"}
MECH = {"Formula": "formula", "Gate": "gate", "WeightTilt": "weight_tilt",
        "Scale": "scale", "Shift": "shift", "Logit": "logit"}
FAMILY = {"Categorical": "categorical", "Lognormal": "lognormal",
          "ZeroInflatedLognormal": "zero_inflated_lognormal",
          "NegativeBinomial": "negative_binomial", "Beta": "beta",
          "TruncatedNormal": "truncated_normal", "DiscreteLump": "discrete_lump",
          "EmpiricalCDF": "empirical_cdf", "Mixture": "mixture", "Constant": "constant"}

_HDR = "# GENERATED by Cardinal Studio from the ontology. Do not hand-edit.\n"


def _deps(onto, uri, chosen):
    out = []
    for dep in onto.subjects(CARD.target, uri):
        src = onto.value(dep, CARD.source)
        if src is not None and local(src) in chosen:
            out.append({"field": local(src),
                        "lag": int(onto.value(dep, CARD.lag) or 0),
                        "mechanism": MECH.get(local(onto.value(dep, CARD.mechanism)), "formula")})
    return sorted(out, key=lambda d: (d["field"], d["lag"]))


def engine_spec_files(onto, design, contract, name: str = "build") -> dict[str, str]:
    """Return {relative_path: yaml_text} for a runnable Cardinal spec bundle."""
    chosen = set(included_fields(design, name))
    fields: dict = {}
    for fid in sorted(chosen):
        uri = BILL[fid]
        entry: dict = {
            "grain": GRAIN.get(local(onto.value(uri, CARD.onGrain)), "account_cycle"),
            "dtype": DTYPE.get(str(onto.value(uri, CARD.dtype) or "decimal"), "float64"),
        }
        deps = _deps(onto, uri, chosen)
        if onto.value(uri, CARD.derived):
            if deps:
                entry["depends_on"] = deps
        else:
            dist = onto.value(uri, CARD.distFamily)
            if dist is not None:
                entry["dist"] = {"family": FAMILY.get(local(dist), "beta")}
                entry["calibration"] = "pending"  # params are Tier-1 calibration work
            if deps:
                entry["depends_on"] = deps
        fields[fid] = entry

    invariants = []
    for iv in onto.subjects(RDF.type, CARD.Invariant):
        g = onto.value(iv, CARD.appliesToGrain)
        row = {"id": local(iv),
               "grain": GRAIN.get(local(g), "account_cycle") if g is not None else "account_cycle",
               "expr": str(onto.value(iv, CARD.expr)),
               "severity": str(onto.value(iv, CARD.severity) or "hard")}
        src = onto.value(iv, DCT_SOURCE)
        if src:
            row["source"] = str(src)
        invariants.append(row)
    invariants.sort(key=lambda x: x["id"])

    portfolio = {"name": "cardinal_studio",
                 "accounts": int(contract.scale.accounts),
                 "cycles": int(contract.scale.cycles),
                 "seed": 42, "out": "data"}

    return {
        "portfolio.yaml": _HDR + yaml.safe_dump(portfolio, sort_keys=False),
        "fields/billing.yaml": _HDR + yaml.safe_dump({"fields": fields}, sort_keys=False, width=100),
        "invariants/billing.yaml": _HDR + yaml.safe_dump({"invariants": invariants}, sort_keys=False, width=100),
    }


def validate_spec_files(files: dict[str, str]) -> dict:
    """Write the bundle to a temp dir and run it through the engine's loader + DAG."""
    tmp = Path(tempfile.mkdtemp(prefix="cardinal_spec_"))
    try:
        for rel, text in files.items():
            path = tmp / rel
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
        from cardinal.spec import load_specs   # engine loader (agents may import engine)
        from cardinal.dag import build_order
        bundle = load_specs(tmp / "portfolio.yaml")
        order = build_order(bundle)
        return {"ok": True,
                "summary": f"{len(bundle.fields)} fields, {len(bundle.invariants)} invariants; "
                           f"calculation order resolves ({len(order)} nodes)."}
    except Exception as exc:  # BuildError or load error
        return {"ok": False, "summary": f"{type(exc).__name__}: {exc}"}
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


def zip_bytes(files: dict[str, str]) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        for rel, text in files.items():
            z.writestr(f"cardinal_spec/{rel}", text)
    return buf.getvalue()
